class SurahModel {
  late String arabic_name;
  String eng_name;
  late int? my_surah_index;
  String? arabic_num;
  String? verses;

  SurahModel(this.arabic_name, this.eng_name,
      {this.my_surah_index, this.arabic_num, this.verses});
}

List<SurahModel> surahModelList = [
  SurahModel("Al-Fatihah", " سُوْرَۃُ الفَاتِحَة",
      my_surah_index: 0, arabic_num: ".١", verses: "Makkah Verses 7"),
  SurahModel("	Al-Baqarah", " سُوْرَۃُ البَقَرَة ",
      my_surah_index: 1, arabic_num: ".٢", verses: "Madinah Verses 286"),
  SurahModel("Ali 'Imran", "سُوْرَۃ آلِ عِمْرَان",
      my_surah_index: 49, arabic_num: ".٣", verses: "Madinah Verses 200"),
  SurahModel("An-Nisa", "سُوْرَۃُ النِّسَاء 	",
      my_surah_index: 76, arabic_num: ".٤", verses: "Madinah Verses 176"),
  SurahModel("Al-Ma'idah", "سُوْرَۃُ المَائِدَة	",
      my_surah_index: 105, arabic_num: ".٥", verses: "Madinah Verses 120"),
  SurahModel("Al-An'am", "سُوْرَۃُ الأَنْعَام	",
      my_surah_index: 127, arabic_num: ".٦", verses: "Makkah Verses 165"),
  SurahModel("Al-A'raf", "سُوْرَۃُ الأَعْرَاف	",
      my_surah_index: 150, arabic_num: ".٧", verses: "Makkah Verses 206"),
  SurahModel("Al-Anfal", "سُوْرَۃُ الأَنْفَال	",
      my_surah_index: 176, arabic_num: ".٨", verses: "Madinah Verses 75"),
  SurahModel("At-Tawbah", "سُوْرَۃُ التَّوْبَة	",
      my_surah_index: 186, arabic_num: ".٩", verses: "Madinah Verses 129"),
  SurahModel("Yunus", "سُوْرَۃ يُونُس	",
      my_surah_index: 207, arabic_num: ".١٠", verses: "Makkah Verses 109"),
  SurahModel("Hud", "سُوْرَۃ هُود	",
      my_surah_index: 220, arabic_num: ".١١", verses: "Makkah Verses 123"),
  SurahModel("Yusuf", "سُوْرَۃ يُوسُف	",
      my_surah_index: 234, arabic_num: ".۱۲", verses: "Makkah Verses 111"),
  SurahModel("Ar-Ra'd", "سُوْرَۃ الرَّعْد	",
      my_surah_index: 248, arabic_num: ".۱۳", verses: "Madinah Verses 43"),
  SurahModel("Ibrahim", "سُوْرَۃُ إِبْرَاهِيم	",
      my_surah_index: 254, arabic_num: ".۱۴", verses: "Makkah Verses 52"),
  SurahModel("Al-Hijr", "سُوْرَۃُ الحِجْر	",
      my_surah_index: 260, arabic_num: ".۱۵", verses: "Makkah Verses 99"),
  SurahModel("An-Nahl", "سُوْرَۃُ النَّحْل	",
      my_surah_index: 266, arabic_num: ".۱٦", verses: "Makkah Verses 128"),
  SurahModel("Al-Isra", "سُوْرَۃُ الإِسْرَاء	",
      my_surah_index: 281, arabic_num: ".۱۷", verses: "Makkah Verses 111"),
  SurahModel("Al-Kahf", "سُوْرَۃ الكَهْف	",
      my_surah_index: 292, arabic_num: ".۱۸", verses: "Makkah Verses 110"),
  SurahModel("Maryam", "سُوْرَۃ مَرْيَم	",
      my_surah_index: 304, arabic_num: ".۱۹", verses: "Makkah Verses 98"),
  SurahModel("Ta-Ha", "سُوْرَۃ طٰهٰ	",
      my_surah_index: 311, arabic_num: ".۲۰", verses: "Makkah Verses 135"),
  SurahModel("Al-Anbiya", "سُوْرَۃُ الأَنْبِيَاء	",
      my_surah_index: 321, arabic_num: ".۲۱", verses: "Makkah Verses 112"),
  SurahModel("Al-Hajj", "سُوْرَۃ الحَجّ	",
      my_surah_index: 330, arabic_num: ".۲۲", verses: "Madinah Verses 128"),
  SurahModel("Al-Mu'minun", "سُوْرَۃُ المُؤْمِنُون	",
      my_surah_index: 341,
      arabic_num: ".۲۳",
      verses: "Makkah Verses Verses 118"),
  SurahModel("Al-Nur", "سُوْرَۃ النُّور	",
      my_surah_index: 349, arabic_num: ".۲۴", verses: "Madinah Verses 64"),
  SurahModel("Al-Furqan", "سُوْرَۃ الفُرْقَان	",
      my_surah_index: 358, arabic_num: ".۲۵", verses: "Makkah Verses 77"),
  SurahModel("Ash-Shu'ara", "سُوْرَۃُ الشُّعَرَاء	",
      my_surah_index: 365, arabic_num: ".۲٦", verses: "Makkah Verses 227"),
  SurahModel("An-Naml", "سُوْرَۃُ النَّمْل	",
      my_surah_index: 375, arabic_num: ".۲۷", verses: "Makkah Verses 93"),
  SurahModel("Al-Qasas", "سُوْرَۃُ القَصَص	",
      my_surah_index: 384, arabic_num: ".۲۸", verses: "Makkah Verses 88"),
  SurahModel("Al-Ankabut", "سُوْرَۃُ العَنْكَبُوت	",
      my_surah_index: 395, arabic_num: ".۲۹", verses: "Makkah Verses 69"),
  SurahModel("Ar-Rum", "سُوْرَۃ الرُّوم	",
      my_surah_index: 403, arabic_num: ".۳۰", verses: "Makkah Verses 60"),
  SurahModel("Luqmaan", "سُوْرَۃ لُقْمَان	",
      my_surah_index: 410, arabic_num: ".۳۱", verses: "Makkah Verses 37"),
  SurahModel("As-Sajdah", "سُوْرَۃُ السَّجْدَة	",
      my_surah_index: 414, arabic_num: ".۳۲", verses: "Makkah Verses 30"),
  SurahModel("Al-Ahzaab", "سُوْرَۃُ الأَحْزَاب	",
      my_surah_index: 417, arabic_num: ".۳۳", verses: "Madinah Verses 73"),
  SurahModel("Saba", "سُوْرَۃ سَبَأ	",
      my_surah_index: 427, arabic_num: ".۳۴", verses: "Makkah Verses 54"),
  SurahModel("Faatir", "سُوْرَۃ فَاطِر	",
      my_surah_index: 433, arabic_num: ".۳۵", verses: "Makkah Verses 45"),
  SurahModel("Ya-Sin", "سُوْرَۃ يٰس	",
      my_surah_index: 439, arabic_num: ".۳٦", verses: "Makkah Verses 83"),
  SurahModel("As-Saaffaat", "سُوْرَۃُ الصَّافَّات	",
      my_surah_index: 444, arabic_num: ".۳۷", verses: "Makkah Verses 182"),
  SurahModel("Saad", "سُوْرَۃ ص	",
      my_surah_index: 451, arabic_num: ".۳۸", verses: "Makkah Verses 88"),
  SurahModel("Az-Zumar", "سُوْرَۃُ الزُّمَر	",
      my_surah_index: 457, arabic_num: ".۳۹", verses: "Makkah Verses 75"),
  SurahModel("Ghafir", "سُوْرَۃ غَافِر	",
      my_surah_index: 466, arabic_num: ".۴۰", verses: "Makkah Verses 85"),
  SurahModel("Fussilat", "سُوْرَۃ فُصِّلَت	",
      my_surah_index: 476, arabic_num: ".۴۱", verses: "Makkah Verses 54"),
  SurahModel("Ash-Shura", "سُوْرَۃُ الشُّورىٰ	",
      my_surah_index: 482, arabic_num: ".۴۲", verses: "Makkah Verses 53"),
  SurahModel("Az-Zukhruf", "سُوْرَۃُ الزُّخْرُف	",
      my_surah_index: 488, arabic_num: ".۲۳", verses: "Makkah Verses 89"),
  SurahModel("Ad-Dukhaan", "سُوْرَۃ الدُّخَان	",
      my_surah_index: 494, arabic_num: ".۴۴", verses: "Makkah Verses 59"),
  SurahModel("Al-Jaathiyah", "سُوْرَۃ الجَاثِيَة	",
      my_surah_index: 497, arabic_num: ".۴۵", verses: "Makkah Verses 37"),
  SurahModel("Al-Ahqaaf", "سُوْرَۃُ الأَحْقَاف	",
      my_surah_index: 501, arabic_num: ".۴٦", verses: "Makkah Verses 35"),
  SurahModel("Muhammad", "سُوْرَۃ مُحَمَّد	",
      my_surah_index: 505, arabic_num: ".۴۷", verses: "Madinah Verses 38"),
  SurahModel("Al-Fath", "سُوْرَۃُ الفَتْح	",
      my_surah_index: 510, arabic_num: ".۴۸", verses: "Madinah Verses 29"),
  SurahModel("Al-Hujuraat", "سُوْرَۃُ الحُجُرَات	",
      my_surah_index: 514, arabic_num: ".۴۹", verses: "Madinah Verses 18"),
  SurahModel("Qaaf", "سُوْرَۃ ق	",
      my_surah_index: 517, arabic_num: ".۵۰", verses: "Makkah Verses 45"),
  SurahModel("Adh-Dhaariyaat", "سُوْرَۃُ الذَّارِيَات	",
      my_surah_index: 519, arabic_num: ".۵۱", verses: "Makkah Verses 60"),
  SurahModel("At-Toor", "سُوْرَۃ الطُّور	",
      my_surah_index: 522, arabic_num: ".۵۲", verses: "Makkah Verses 49"),
  SurahModel("An-Najm", "سُوْرَۃُ النَّجْم	",
      my_surah_index: 525, arabic_num: ".۵۳", verses: "Makkah Verses 69"),
  SurahModel("Al-Qamar", "سُوْرَۃُ القَمَر	",
      my_surah_index: 527, arabic_num: ".۵۴", verses: "Makkah Verses 55"),
  SurahModel("Ar-Rahman", "سُوْرَۃ الرَّحْمَٰن	",
      my_surah_index: 530, arabic_num: ".۵۵", verses: "Madinah Verses 78"),
  SurahModel("Al-Waqi'a", "سُوْرَۃُ الوَاقِعَة	",
      my_surah_index: 533, arabic_num: ".۵٦", verses: "Makkah Verses 96"),
  SurahModel("Al-Hadeed", "سُوْرَۃُ الحَدِيد	",
      my_surah_index: 536, arabic_num: ".۵۷", verses: "Madinah Verses 29"),
  SurahModel("Al-Mujadila", "سُوْرَۃُ المُجَادِلَة	",
      my_surah_index: 541, arabic_num: ".۵۸", verses: "Madinah Verses 22"),
  SurahModel("Al-Hashr", "سُوْرَۃُ الحَشْر	",
      my_surah_index: 544, arabic_num: ".۵۹", verses: "Madinah Verses 24"),
  SurahModel("Al-Mumtahanah", "سُوْرَۃُ المُمْتَحَنَة	",
      my_surah_index: 548, arabic_num: ".٦۰", verses: "Madinah Verses 13"),
  SurahModel("As-Saff", "سُوْرَۃُ الصَّفّ	",
      my_surah_index: 550, arabic_num: ".٦۱", verses: "Madinah Verses 14"),
  SurahModel("Al-Jumu'ah", "سُوْرَۃُ الجُمُعَة	",
      my_surah_index: 552, arabic_num: ".٦۲", verses: "Madinah Verses 11"),
  SurahModel("Al-Munafiqoon", "سُوْرَۃُ المُنَافِقُون	",
      my_surah_index: 553, arabic_num: ".٦۳", verses: "Madinah Verses 11"),
  SurahModel("At-Taghabun", "سُوْرَۃُ التَّغَابُن	",
      my_surah_index: 555, arabic_num: ".٦۴", verses: "Madinah Verses 18"),
  SurahModel("At-Talaq", "سُوْرَۃُ الطَّلَاق	",
      my_surah_index: 557, arabic_num: ".٦۵", verses: "Madinah Verses 12"),
  SurahModel("At-Tahreem", "سُوْرَۃُ التَّحْرِيم	",
      my_surah_index: 559, arabic_num: ".٦٦", verses: "Madinah Verses 12"),
  SurahModel("Al-Mulk", "سُوْرَۃُ المُلْك	",
      my_surah_index: 561, arabic_num: ".٦۷", verses: "Makkah Verses 30"),
  SurahModel("Al-Qalam", "سُوْرَۃ القَلَم	",
      my_surah_index: 563, arabic_num: ".٦۸", verses: "Makkah Verses 52"),
  SurahModel("Al-Haaqqa", "سُوْرَۃ الحَاقَّة	",
      my_surah_index: 566, arabic_num: ".٦۹", verses: "Makkah Verses 52"),
  SurahModel("Al-Ma'aarij", "سُوْرَۃُ المَعَارِج	",
      my_surah_index: 568, arabic_num: ".۷۰", verses: "Makkah Verses 44"),
  SurahModel("Nuh", "سُوْرَۃ نُوح	",
      my_surah_index: 570, arabic_num: ".۷۱", verses: "Makkah Verses 28"),
  SurahModel("Al-Jinn", "سُوْرَۃُ الجِنّ	",
      my_surah_index: 572, arabic_num: ".۷۲", verses: "Makkah Verses 28"),
  SurahModel("Al-Muzzammil", "سُوْرَۃُ المُزَّمِّل	",
      my_surah_index: 575, arabic_num: ".۷۳", verses: "Makkah Verses 20"),
  SurahModel("Al-Muddaththir", "سُوْرَۃُ المُدَّثِّر	",
      my_surah_index: 577, arabic_num: ".۷۴", verses: "Makkah Verses 58"),
  SurahModel("Al-Qiyamah", "سُوْرَۃُ القِيَامَة	",
      my_surah_index: 579, arabic_num: ".۷۵", verses: "Makkah Verses 40"),
  SurahModel("Al-Insaan", "سُوْرَۃُ الإِنْسَان	",
      my_surah_index: 581, arabic_num: ".۷٦", verses: "Madinah Verses 31"),
  SurahModel("Al-Mursalaat", "سُوْرَۃُ المُرْسَلَات	",
      my_surah_index: 583, arabic_num: ".۷۷", verses: "Makkah Verses 50"),
  SurahModel("An-Naba'", "سُوْرَۃُ النَّبَأ	",
      my_surah_index: 585, arabic_num: ".۷۸", verses: "Makkah Verses 40"),
  SurahModel("An-Naazi'aat", "سُوْرَۃُ النَّازِعَات	",
      my_surah_index: 586, arabic_num: ".۷۹", verses: "Makkah Verses 46"),
  SurahModel("Abasa", "سُوْرَۃ عَبَسَ	",
      my_surah_index: 588, arabic_num: ".۸۰", verses: "Makkah Verses 42"),
  SurahModel("At-Takweer", "سُوْرَۃُ التَّكْوِير	",
      my_surah_index: 589, arabic_num: ".۸۱", verses: "Makkah Verses 29"),
  SurahModel("Al-Infitar", "سُوْرَۃُ الإِنْفِطَار	",
      my_surah_index: 590, arabic_num: ".۸۲", verses: "Makkah Verses 19"),
  SurahModel("Al-Mutaffifeen", "سُوْرَۃُ المُطَفِّفِين	",
      my_surah_index: 591, arabic_num: ".۸۳", verses: "Makkah Verses 36"),
  SurahModel("Al-Inshiqaaq", "سُوْرَۃُ الإِنْشِقَاق	",
      my_surah_index: 593, arabic_num: ".۸۴", verses: "Makkah Verses 25"),
  SurahModel("Al-Burooj", "سُوْرَۃُ البُرُوج	",
      my_surah_index: 594, arabic_num: ".۸۵", verses: "Makkah Verses 22"),
  SurahModel("At-Taariq", "سُوْرَۃُ الطَّارِق	",
      my_surah_index: 595, arabic_num: ".۸٦", verses: "Makkah Verses 17"),
  SurahModel("Al-A'la", "سُوْرَۃُ الأَعْلَىٰ	",
      my_surah_index: 596, arabic_num: ".۸۷", verses: "Makkah Verses 19"),
  SurahModel("Al-Ghaashiyah", "سُوْرَۃُ الغَاشِيَة	",
      my_surah_index: 596, arabic_num: ".۸۸", verses: "Makkha Verses 26"),
  SurahModel("Al-Fajr", "سُوْرَۃُ الفَجْر	",
      my_surah_index: 597, arabic_num: ".۸۹", verses: "Makkah Verses 30"),
  SurahModel("Al-Balad", "سُوْرَۃُ البَلَد	",
      my_surah_index: 599, arabic_num: ".۹۰", verses: "Makkah Verses 20"),
  SurahModel("Ash-Shams", "سُوْرَۃُ الشَّمْس	",
      my_surah_index: 599, arabic_num: ".۹۱", verses: "Makkah Verses 15"),
  SurahModel("Al-Layl", "سُوْرَۃُ اللَّيْل	",
      my_surah_index: 600, arabic_num: ".۹۲", verses: "Makkah Verses 21"),
  SurahModel("Ad-Dhuha", "سُوْرَۃُ الضُّحَىٰ	",
      my_surah_index: 601, arabic_num: ".۹۳", verses: "Makkah Verses 11"),
  SurahModel("Ash-Sharh", "سُوْرَۃُ الشَّرْح	",
      my_surah_index: 601, arabic_num: ".۹۴", verses: "Makkah Verses 8"),
  SurahModel("At-Tin", "سُوْرَۃُ التِّين	",
      my_surah_index: 602, arabic_num: ".۹۵", verses: "Makkah Verses 8"),
  SurahModel("Al-Alaq", "سُوْرَۃُ العَلَق	",
      my_surah_index: 602, arabic_num: ".۹٦", verses: "Makkah Verses 19"),
  SurahModel("Al-Qadr", "سُوْرَۃُ القَدْر	",
      my_surah_index: 603, arabic_num: ".۹۷", verses: "Makkah Verses 5"),
  SurahModel("Al-Bayyinahh", "سُوْرَۃُ البَيِّنَة	",
      my_surah_index: 603, arabic_num: ".۹۸", verses: "Madinah Verses 8"),
  SurahModel("Az-Zalzalah", "سُوْرَۃُ الزَّلْزَلَة	",
      my_surah_index: 604, arabic_num: ".۹۹", verses: "Madinah Verses 8"),
  SurahModel("Al-'Adiyat", "سُوْرَۃُ العَادِيَات	",
      my_surah_index: 604, arabic_num: ".۱۰۰", verses: "Makkah Verses 11"),
  SurahModel("Al-Qaari'ah", "سُوْرَۃُ القَارِعَة	",
      my_surah_index: 605, arabic_num: ".۱۰۱", verses: "Makkah Verses 11"),
  SurahModel("At-Takathur", "سُوْرَۃُ التَّكَاثُر	",
      my_surah_index: 605, arabic_num: ".۱۰۲", verses: "Makkah Verses 8"),
  SurahModel("Al-'Asr", "سُوْرَۃُ العَصْر	",
      my_surah_index: 606, arabic_num: ".۱۰۳", verses: "Makkah Verses 3"),
  SurahModel("Al-Humazah", "سُوْرَۃُ الهُمَزَة	",
      my_surah_index: 606, arabic_num: ".۱۰۴", verses: "Makkah Verses 9"),
  SurahModel("Al-Fil", "سُوْرَۃُ الفِيل	",
      my_surah_index: 606, arabic_num: ".۱۰۵", verses: "Makkah Verses 5"),
  SurahModel("Quraysh", "سُوْرَۃ قُرَيْش	",
      my_surah_index: 607, arabic_num: ".۱۰٦", verses: "Makkah Verses 4"),
  SurahModel("Al-Maa'oon", "سُوْرَۃُ المَاعُون	p",
      my_surah_index: 607, arabic_num: ".۱۰۷", verses: "Makkha Verses 7"),
  SurahModel("Al-Kawthar", "سُوْرَۃُ الكَوْثَر	",
      my_surah_index: 607, arabic_num: ".۱۰۸", verses: "Makkah Verses 3"),
  SurahModel("Al-Kaafiroon", "سُوْرَۃُ الكَافِرُون	",
      my_surah_index: 607, arabic_num: ".۱۰۹", verses: "Makkah Verses 6"),
  SurahModel("An-Nasr", "سُوْرَۃُ النَّصْر	",
      my_surah_index: 608, arabic_num: ".۱۱۰", verses: "Makkah Verses 3"),
  SurahModel("Al-Masad", "سُوْرَۃُ المَسَد	",
      my_surah_index: 608, arabic_num: ".۱۱۱", verses: "Makkah Verses 5"),
  SurahModel("Al-Ikhlaas", "سُوْرَۃُ الإِخْلَاص	",
      my_surah_index: 608, arabic_num: ".۱۱۲", verses: "Makkah Verses 4"),
  SurahModel("Al-Falaq", "سُوْرَۃُ الفَلَق	",
      my_surah_index: 609, arabic_num: ".۱۱۳", verses: "Makkah Verses 5"),
  SurahModel("An-Naas", "سُوْرَۃُ النَّاس	",
      my_surah_index: 609, arabic_num: ".۱۱۴", verses: "Makkah Verses 4"),
];
